namespace :minecraft do
  # Clean up all files autogenerated by minecraft. Lots can be spewed about while developing
  task :clean do
    `rm -r server.log server.properties world ops.txt banned-ips.txt banned-players.txt`
  end

end
